/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.ExamController;
import Controllers.ExportController;
import Controllers.NewExamController;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SinhVienBK
 */
public class ExamViewing extends javax.swing.JPanel {

    /**
     * Creates new form Exam
     */
    public ExamViewing() {
        initComponents();
    }
    
    public JPanel getJPanelExam() {
        return background;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        delete = new javax.swing.JMenuItem();
        export = new javax.swing.JMenuItem();
        doingExam = new javax.swing.JMenuItem();
        background = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableExam = new javax.swing.JTable();
        exam = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblShowingMode = new javax.swing.JLabel();
        cboShowingMode = new javax.swing.JComboBox();

        delete.setText("Xóa");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPopupMenu1.add(delete);

        export.setText("Export to PDF");
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });
        jPopupMenu1.add(export);

        doingExam.setText("Làm bài thử");
        doingExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doingExamActionPerformed(evt);
            }
        });
        jPopupMenu1.add(doingExam);

        background.setBackground(new java.awt.Color(233, 235, 238));
        background.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                backgroundAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(233, 235, 238));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableExam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên đề thi", "Ngày tạo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableExam.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableExam.setGridColor(new java.awt.Color(233, 235, 238));
        tableExam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableExamMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableExamMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableExam);
        if (tableExam.getColumnModel().getColumnCount() > 0) {
            tableExam.getColumnModel().getColumn(0).setPreferredWidth(70);
            tableExam.getColumnModel().getColumn(1).setResizable(false);
            tableExam.getColumnModel().getColumn(1).setPreferredWidth(300);
            tableExam.getColumnModel().getColumn(2).setResizable(false);
            tableExam.getColumnModel().getColumn(2).setPreferredWidth(150);
        }

        exam.setBackground(new java.awt.Color(233, 235, 238));
        exam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exam.setMinimumSize(new java.awt.Dimension(0, 0));
        exam.setPreferredSize(new java.awt.Dimension(680, 446));
        exam.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton1.setText("Tạo mới");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblShowingMode.setText("Hiển thị theo: ");

        cboShowingMode.setModel(ExamController.getNameSubjects());
        cboShowingMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboShowingModeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblShowingMode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboShowingMode, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(exam, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblShowingMode)
                        .addComponent(cboShowingMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                    .addComponent(exam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        ExamController.deleteExam(tableExam, exam);
    }//GEN-LAST:event_deleteActionPerformed

    private void tableExamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableExamMouseClicked
        ExamController.showExam(tableExam, exam);
    }//GEN-LAST:event_tableExamMouseClicked

    private void tableExamMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableExamMouseReleased
        DefaultTableModel model = (DefaultTableModel) tableExam.getModel();
        int selectRow = tableExam.getSelectedRow();
        if (selectRow != -1 && evt.isPopupTrigger()) {
            delete.setVisible(true);
            //show.setVisible(true);
            jPopupMenu1.show(tableExam, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tableExamMouseReleased

    private void backgroundAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_backgroundAncestorAdded

    }//GEN-LAST:event_backgroundAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NewExamController.viewNewExam();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
        ExportController.showSavePath(tableExam);
    }//GEN-LAST:event_exportActionPerformed

    private void cboShowingModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboShowingModeActionPerformed
        // TODO add your handling code here:
        ExamController.loadTableExam(tableExam, cboShowingMode.getSelectedItem());
    }//GEN-LAST:event_cboShowingModeActionPerformed

    private void doingExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doingExamActionPerformed
        Controllers.ExamController.doingExam(tableExam);
    }//GEN-LAST:event_doingExamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JComboBox cboShowingMode;
    private javax.swing.JMenuItem delete;
    private javax.swing.JMenuItem doingExam;
    private javax.swing.JPanel exam;
    private javax.swing.JMenuItem export;
    private javax.swing.JButton jButton1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblShowingMode;
    public javax.swing.JTable tableExam;
    // End of variables declaration//GEN-END:variables
}
