/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Duc Dung Dan
 */
public class Subjects extends javax.swing.JPanel {

    /**
     * Creates new form Subjects
     */
    public Subjects() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        editSubject = new javax.swing.JMenuItem();
        deleteSubject = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        editChapter = new javax.swing.JMenuItem();
        deleteChapter = new javax.swing.JMenuItem();
        background = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSubjects = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableChapters = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        editSubject.setText("Chỉnh sửa");
        editSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSubjectActionPerformed(evt);
            }
        });
        jPopupMenu1.add(editSubject);

        deleteSubject.setText("xóa");
        deleteSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSubjectActionPerformed(evt);
            }
        });
        jPopupMenu1.add(deleteSubject);

        editChapter.setText("Chỉnh sửa");
        editChapter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editChapterActionPerformed(evt);
            }
        });
        jPopupMenu2.add(editChapter);

        deleteChapter.setText("xóa");
        deleteChapter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteChapterActionPerformed(evt);
            }
        });
        jPopupMenu2.add(deleteChapter);

        background.setBackground(new java.awt.Color(233, 235, 238));
        background.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                backgroundAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(233, 235, 238));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableSubjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Môn học", "Số chương"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSubjects.setGridColor(new java.awt.Color(233, 235, 238));
        tableSubjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSubjectsMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableSubjectsMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableSubjects);
        if (tableSubjects.getColumnModel().getColumnCount() > 0) {
            tableSubjects.getColumnModel().getColumn(0).setResizable(false);
            tableSubjects.getColumnModel().getColumn(1).setResizable(false);
            tableSubjects.getColumnModel().getColumn(2).setResizable(false);
        }

        tableChapters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên chương"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableChapters.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableChapters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableChaptersMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tableChapters);
        if (tableChapters.getColumnModel().getColumnCount() > 0) {
            tableChapters.getColumnModel().getColumn(0).setResizable(false);
            tableChapters.getColumnModel().getColumn(0).setPreferredWidth(80);
            tableChapters.getColumnModel().getColumn(1).setResizable(false);
            tableChapters.getColumnModel().getColumn(1).setPreferredWidth(510);
        }

        jButton1.setText("New subject");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("New chapter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(29, 29, 29)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableSubjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSubjectsMouseClicked
        Controllers.SubjectController.viewChapter(tableSubjects, tableChapters);
    }//GEN-LAST:event_tableSubjectsMouseClicked

    private void tableSubjectsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSubjectsMouseReleased
        DefaultTableModel model = (DefaultTableModel) tableSubjects.getModel();
        int selectRow = tableSubjects.getSelectedRow();
        if (selectRow != -1 && evt.isPopupTrigger()) {
            jPopupMenu1.show(tableSubjects, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tableSubjectsMouseReleased

    private void backgroundAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_backgroundAncestorAdded
        Controllers.SubjectController.viewSubject(tableSubjects);
    }//GEN-LAST:event_backgroundAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Controllers.SubjectController.addSubject(tableSubjects);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Controllers.SubjectController.viewAddChapter(tableSubjects, tableChapters);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void deleteChapterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteChapterActionPerformed
        Controllers.SubjectController.deleteChapter(tableSubjects, tableChapters);
    }//GEN-LAST:event_deleteChapterActionPerformed

    private void tableChaptersMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableChaptersMouseReleased
        DefaultTableModel model = (DefaultTableModel) tableChapters.getModel();
        int selectRow = tableChapters.getSelectedRow();
        if (selectRow != -1 && evt.isPopupTrigger()) {
            jPopupMenu2.show(tableChapters, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tableChaptersMouseReleased

    private void deleteSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSubjectActionPerformed
        Controllers.SubjectController.deleteSubject(tableSubjects);
    }//GEN-LAST:event_deleteSubjectActionPerformed

    private void editChapterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editChapterActionPerformed
        Controllers.SubjectController.viewEditChapter(tableSubjects, tableChapters);
    }//GEN-LAST:event_editChapterActionPerformed

    private void editSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSubjectActionPerformed
        Controllers.SubjectController.editSubject(tableSubjects);
    }//GEN-LAST:event_editSubjectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel background;
    private javax.swing.JMenuItem deleteChapter;
    private javax.swing.JMenuItem deleteSubject;
    private javax.swing.JMenuItem editChapter;
    private javax.swing.JMenuItem editSubject;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableChapters;
    public javax.swing.JTable tableSubjects;
    // End of variables declaration//GEN-END:variables
}
